vtk_module(vtkIOGDAL
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkIOImage
  TEST_DEPENDS
    vtkTestingCore
    vtkRenderingOpenGL
    vtkTestingRendering
    vtkInteractionStyle
)
